language: java
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential
  - mkdir protobuf_install
  - pushd protobuf_install
  - wget https://github.com/google/protobuf/releases/download/v2.5.0/protobuf-2.5.0.tar.gz
  - tar xzf protobuf-2.5.0.tar.gz
  - cd  protobuf-2.5.0
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - protoc --version
  - popd
  - pwd
  - sudo apt-get install -qq libboost-dev libboost-test-dev libboost-program-options-dev libevent-dev automake libtool flex bison pkg-config g++ libssl-dev
  # - wget -nv http://archive.apache.org/dist/thrift/0.7.0/thrift-0.7.0.tar.gz
  - tar zxf thrift-0.7.0.tar.gz
  - cd thrift-0.7.0
  - chmod +x ./configure
  - ./configure --disable-gen-erl --disable-gen-hs --without-ruby --without-haskell --without-erlang
  - mvn install:install-file -DgroupId=org.apache.httpcomponents -DartifactId=httpclient -Dversion=4.0.1 -Dpackaging=jar -Dfile=./httpclient-4.0.1.jar
  - mvn install:install-file -DgroupId=org.slf4j -DartifactId=slf4j-api -Dversion=1.5.8 -Dpackaging=jar -Dfile=./slf4j-api-1.5.8.jar
  - mvn install:install-file -DgroupId=javax.servlet -DartifactId=servlet-api -Dversion=2.5 -Dpackaging=jar -Dfile=./servlet-api-2.5.jar
  - mvn install:install-file -DgroupId=commons-lang -DartifactId=commons-lang -Dversion=2.5 -Dpackaging=jar -Dfile=./commons-lang-2.5.jar
  - sudo make install
  - cd ..

env:
  - HADOOP_PROFILE=hadoop-1 TEST_CODECS=uncompressed
  - HADOOP_PROFILE=default TEST_CODECS=gzip,snappy

install: mvn install --batch-mode -DskipTests=true -Dmaven.javadoc.skip=true -Dsource.skip=true > mvn_install.log || mvn install --batch-mode -DskipTests=true -Dmaven.javadoc.skip=true -Dsource.skip=true > mvn_install.log || (cat mvn_install.log && false)
script: mvn test -P $HADOOP_PROFILE
